<?php $incompatiblePlugins = $block->getIncompatiblePlugins();
if(count($incompatiblePlugins) == 0) {
    return;
}
?>

<h2>We have found some outdated plugins</h2>
<p>These plugins are currently installed, but only support the 'UA' Measurement Protocol, which is not supported in Adwise Analytics v2.0.0 and higher</p>
<p>Please uninstall these plugins, or update them to the new 'GA4' implementation</p>
<ul>
    <?php foreach ($incompatiblePlugins as $plugin): ?>
        <li><?= $plugin ?></li>
    <?php endforeach; ?>
</ul>
